### ISSUE TITLE
Tratar corretamente SIGTERM

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/async-worker#108]
Atualmente, um processo do asyncworker é "impossível" de desligar corretamente. Apenas com `kill -9`, o que é muito ruim.

Esse é o erro quando o processo recebe um `SIGTERM`.

```
Task exception was never retrieved
future: <Task finished coro=<Signal.send() done, defined at /home/daltonmatos/.local/share/virtualenvs/math-uservice-mOodna-Q/lib/python3.7/site-packages/asyncworker/signals/base.py:32> exception=RuntimeError('Cannot send on frozen signal.')>
Traceback (most recent call last):
  File "/home/daltonmatos/.local/share/virtualenvs/math-uservice-mOodna-Q/lib/python3.7/site-packages/asyncworker/signals/base.py", line 37, in send
    raise RuntimeError("Cannot send on frozen signal.")
RuntimeError: Cannot send on frozen signal.
```
A cada `SIGTERM` enviado, vemos o mesmo traceback.

# O que fazer

O que temos que fazer é:

- Receber o SIGTERM
- Chamar o `shutdown` de cada um dos `SignalHandlers`
- Desligar o loop principal
- `sys.exit(0)`, se não tivermos encontrado nenhum problema no processo de shutdown.

**Comment by daltonmatos** [comment]
@diogommartins

**Comment by diogommartins** [comment]
Quis evitar o `sys.exit(0)` pra evitar que isso aconteça:

Imagina que temos um `asyncworker.App` e o seguinte trecho de código no nosso `__main__`:
```python
# ....
app.run()
print("eu nunca seria chamado")
```
Acho que seríamos meio invasivos se o asyncworker fosse o responsável por finalizar o processo e não daríamos pro cliente do framework a possibilidade de ter outras lógicas no mesmo processo

**Comment by daltonmatos** [comment]
Faz sentido, melhor assim mesmo. :tada:
