### ISSUE TITLE
Atualizar pydantic no setup.py

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/async-worker#134]
Atualmente estamos usando ´pydandic==0.28` mas podemos atualizar para o `pydantic==0.30`.

Bônus: Checar se dá pra ir para última versão do pydantic.

**Comment by Fayhen** [comment]
Farei isto.

Acredito que as atualizações feitas do `pydantic 0.28` para o `0.30` não irão necessariamente afetar seu código. Uma busca simples no repositório indica que o `async-worker` utiliza o `pydantic` especificamente pelas classes `BaseSettings`, `BaseModel` e o decorator `validator`. As mudanças indicadas no changelog das versões `0.29` e `0.30` não indicam que houveram alterações nesse código, ao invés havendo atualizações de documentação, alguns enhancements e vários fixes (`GenericModel`, recursões, geração de schemas) que não afetam as funcionalidades diretamente utilizadas pelo `async-worker`.

Adicionalmente, notei que ambos seu `pipfile` e `pipfile.lock` contém a versão `0.30` do `pydantic`. Utilizar o `pipenv` pra instalar as dependências do `async-worker` acaba por já instalar esta versão, o que pode ser verificado utilizando pip freeze em um terminal com o ambiente virtual ativado.

Atualizar pras versões `1.0b1` e `1.0b2`, por outro lado irá requerer mais cuidado. Existe reorganização em como se dá o parsing de URLs, mudanças nos defaults do `BaseSettings` e em como a classe lê variáveis de ambiente, alterações em dunder methods da classe `BaseModel` (`__getattr__`, `__values__` renomeado pra `__dict__`), entre várias outras modificações. É necessário testar e analisar com calma se as versões mais recentes irão modificar o comportamento do `async-worker`.

**Comment by daltonmatos** [comment]
Obrigado @Fayhen !! De fato no `.lock` já está o `0.30` mesmo. Só percebi que no `setup.py` estava o `.28` depois que já estava tudo preparado para fechar a nova versão do asyncworker (`0.11.0`). Por isso abri a issue justamente para não esquecer.
