### ISSUE TITLE
Criar um mecanismo para podermos marcar tempo de execução de código

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/async-worker#2]
A ideia é podermos "cercar" algum trecho de código e podermos saber quanto tempo esse trecho de código demou pra rodar. Exemplo:

```python
        async with Timeit(name="index-counts-per-app", callback=coroutine, **kwargs):
            await self.elasticsearch.index(index=index_name, doc_type="counts", body=indexed_document)
```

A idéia é que esse context manager faça a medição do tempo que ele levou entre o `__aenter()__` e o `__aexit()__` e chamará o `callback` passando:

* name;
* time (em millisegundos);
* Quaisquer outros kwargs que tenham sido passados pra ele;

É de responsabilidade do callback fazer alguma coisa com essa inormação.

Pontos importantes:
* O callback **deve** ser assíncrono.

@diogommartins @dnp1

**Comment by diogommartins** [comment]
To fazendo esse :D

**Comment by daltonmatos** [comment]
Boa!! Obrigado! Depois posta aqui a ideia e uns pseudo códigos pra podermos discutir a implementação. 🎉🎉

**Comment by diogommartins** [comment]
Abri um PR com uma implementação já. A gente pode discutir lá

**Comment by daltonmatos** [comment]
Combinado!
