### ISSUE TITLE
Adicionar validação automática de PEP8 com Flake8

### ISSUE THREAD

**Issue by diogommartins** [B2W-BIT/async-worker#29]

**Comment by daltonmatos** [comment]
Acho podemos trocar o flake8 por um formatter que já ajusta código para o jeito correto. O flake8 também é um formatter? Se sim, até pode ser ele mesmo.

Se não, acho que vale uma olhada no Black. https://github.com/ambv/black

**Comment by diogommartins** [comment]
@daltonmatos Dei uma olhada no black escurti bastante! Ele faz coisas que o flake8 não faz e acho que deveríamos testar ele. Posso fazer um PR. Fiquei bem animado :D

**Comment by daltonmatos** [comment]
Maravilha! Manda ver! Faz um commit adicoinando o black na pipeline e outro commit com todas as formatações pendentes. Quando fizermos o merge pra master já passa a valer pra todo mundo. :tada:

**Comment by diogommartins** [comment]
Done
