### ISSUE TITLE
Implementar @app.run_every(seconds=X, options={})

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/async-worker#45]
Existem workers que são, na verdade, apenas producers. Nesse caso não temos nenhum tipo de "input" para eles que o async-worker poderia fornecer.

Um exemplo é um producer que recebe seu input incial via envvar, como é o caso do [stats-collector](/b2w-bit/asgard-app-stats-collector). Esse worker boota, faz a coleta dos dados, deposita em algum lugar e depois morre.

Depois de um tempo ele roda novamente e faz a mesma coisa. Essa foi a inspiração para a implementação do `@app.run_every()`.

Duas opções que já vejo como necessárias:

* Recorrência dos runs. Por enquanto pode ser apenas um número em segundos. Podemos fornecer algumas constantes que facilitem o cálculo para intervalor longos;
* Concorrência máxima: Quantas rotinas poderão estar rodando de forma concorrente em um mesmo intervalo?

```python

from asyncworker import App
from asyncworker.options import Options

app = App()

@app.run_every(seconds=10, options={Options.MAX_CONCURRENCY: 3})
async def main():
      # code
      ...
      ...
```

Nesse código de exemplo a corotina `main()` será chamada a cada 10 segundos, mas no máximo 3 cópias desse corotina estarão rodando de forma concorrente em um mesmo instante de tempo.

**Comment by daltonmatos** [comment]
@diogommartins

**Comment by diogommartins** [comment]
A ideia é que o valor de `MAX_CONCURRENCY` sirva como input de um semáforo? Vamos considerar o seguinte cenário como exemplo:

- `main()` leva em média `60 seconds` para rodar, então quando a _segunda chamada_ rolar, a primeira chamada ainda vai estar rodando. E o mesmo vai acontecer com a _terceira chamada_.
- em `T=40 seconds` uma quarta instância vai tentar rodar e vai ser impedida porque já tem 3 rodando, que é valor máximo definido em `MAX_CONCURRENCY`. Nesse momento, o que tem que acontecer com essa chamada ? Ela deve ser enfileirada e rodar quando uma das primeiras terminar, ou deve simplesmente ser ignorada?

Indo pelo primeiro caminho, o cenário de enfileiramento gerado pelo semáforo pode gerar alguns side-effects indesejados. Levando esse exemplo em consideração e fazendo uma progressão simples, da pra gente assumir que ao longo do tempo, a quantidade de corotinas enfileiradas só vai crescer e nunca vai diminuir, o que pra app vai representar um aumento de memória pequeno, lento, mas sempre constante.

```python
import asyncio
import os

COROS = 0
SPEED = 1  # velocidade que a simulação deve rodar SPEED=1 é tempo real e SPEED=1000 é mil vezes mais rápido


async def do_something():
    global COROS

    print("Doing something")
    await asyncio.sleep(60 / SPEED)
    COROS -= 1
    print("Done")


async def wrapper(semaphore, coro):
    async with semaphore:
        await coro


async def main(seconds=10, max_concurreny=3):
    global COROS

    semaphore = asyncio.Semaphore(max_concurreny)

    while True:
        asyncio.ensure_future(wrapper(semaphore, do_something()))
        COROS += 1
        print(f"Future created. Currently running: {COROS}")
        await asyncio.sleep(seconds / SPEED)


print(f"Iniciando app. Pid: {os.getpid()}")
asyncio.run(main())
```

Se simplesmente ignoramos, o uso de memória vai ser constante, mas pode ser que as chamadas aconteçam em um intervalo maior do que 10 segundos:

```python
import asyncio
import os

COROS = 0
SPEED = 100000  # velocidade que a simulação deve rodar


async def do_something():
    global COROS

    print("Doing something")
    await asyncio.sleep(60 / SPEED)
    COROS -= 1
    print("Done")


async def wrapper(semaphore, coro):
    async with semaphore:
        await coro


async def main(seconds=10, max_concurreny=3):
    global COROS

    semaphore = asyncio.Semaphore(max_concurreny)

    while True:
        if COROS < max_concurreny:
            asyncio.ensure_future(wrapper(semaphore, do_something()))
            COROS += 1
        print(f"Future created. Currently running: {COROS}")
        await asyncio.sleep(seconds / SPEED)


print(f"Iniciando app. Pid: {os.getpid()}")
asyncio.run(main())
```

Acho que uma implementação ideal teria um "timer" que a cada 10 segundos, chamaria a corotina registrada, até que atingisse o tamanho máximo. Quando o tamanho máximo é atingido, para o timer, até que a corotina termine e uma nova possa ser chamada e o timer seja resetado

**Comment by diogommartins** [comment]
Acho que esse é um rascunho de implementação com o comportamento esperado:

```python
import asyncio
import os

COROS = 0
SPEED = 1  # velocidade que a simulação deve rodar SPEED=1 é tempo real e SPEED=1000 é mil vezes mais rápido

coro_is_done: asyncio.Event


async def do_something():
    global COROS

    print("Doing something")
    await asyncio.sleep(60 / SPEED)
    COROS -= 1
    print("Done")
    coro_is_done.set()


async def wrapper(semaphore, coro):
    async with semaphore:
        await coro


async def main(seconds=10, max_concurreny=3):
    global COROS, coro_is_done

    semaphore = asyncio.Semaphore(max_concurreny)
    coro_is_done = asyncio.Event()

    while True:
        if COROS < max_concurreny:
            asyncio.ensure_future(wrapper(semaphore, do_something()))
            COROS += 1
        print(f"Future created. Currently running: {COROS}")
        await asyncio.wait(
            (
                coro_is_done.wait(),
                asyncio.sleep(seconds / SPEED)
            ),
            return_when=asyncio.FIRST_COMPLETED
        )
        coro_is_done.clear()


print(f"Iniciando app. Pid: {os.getpid()}")
asyncio.run(main())
```

**Comment by diogommartins** [comment]
Isso é mais simples e tem o mesmo efeito:

```python
import asyncio
import os

COROS = 0
SPEED = 1  # velocidade que a simulação deve rodar SPEED=1 é tempo real e SPEED=1000 é mil vezes mais rápido

coro_is_done: asyncio.Event


async def do_something():
    global COROS

    print("Doing something")
    await asyncio.sleep(60 / SPEED)
    COROS -= 1
    print("Done")
    coro_is_done.set()


async def wrapper(semaphore, coro):
    async with semaphore:
        await coro


async def main(seconds=10, max_concurreny=3):
    global COROS, coro_is_done

    semaphore = asyncio.Semaphore(max_concurreny)
    coro_is_done = asyncio.Event()

    while True:
        if COROS < max_concurreny or await coro_is_done.wait():
            asyncio.ensure_future(wrapper(semaphore, do_something()))
            COROS += 1
        print(f"Future created. Currently running: {COROS}")
        await asyncio.sleep(seconds / SPEED)
        coro_is_done.clear()


print(f"Iniciando app. Pid: {os.getpid()}")
asyncio.run(main())
```

**Comment by diogommartins** [comment]
> Isso é mais simples e tem o mesmo efeito:
> 
> ```python
> import asyncio
> import os
> 
> COROS = 0
> SPEED = 1  # velocidade que a simulação deve rodar SPEED=1 é tempo real e SPEED=1000 é mil vezes mais rápido
> 
> coro_is_done: asyncio.Event
> 
> 
> async def do_something():
>     global COROS
> 
>     print("Doing something")
>     await asyncio.sleep(60 / SPEED)
>     COROS -= 1
>     print("Done")
>     coro_is_done.set()
> 
> 
> async def wrapper(semaphore, coro):
>     async with semaphore:
>         await coro
> 
> 
> async def main(seconds=10, max_concurreny=3):
>     global COROS, coro_is_done
> 
>     semaphore = asyncio.Semaphore(max_concurreny)
>     coro_is_done = asyncio.Event()
> 
>     while True:
>         if COROS < max_concurreny or await coro_is_done.wait():
>             asyncio.ensure_future(wrapper(semaphore, do_something()))
>             COROS += 1
>         print(f"Future created. Currently running: {COROS}")
>         await asyncio.sleep(seconds / SPEED)
>         coro_is_done.clear()
> 
> 
> print(f"Iniciando app. Pid: {os.getpid()}")
> asyncio.run(main())
> ```

Esse exemplo não usa o semáforo pra nada. [Removi ele aqui](https://github.com/B2W-BIT/async-worker/commit/ed14bc7cdd6fcfc645a92e5be1b59eef32024278)

**Comment by daltonmatos** [comment]
Acho que deveríamos ignorar as chamadas que não podem ser feitas mas ao mesmo tempo gerar métricas que mostrem isso, por exemplo:

* Tempo médio entre cada chamada de uma nova task

Se esse tempo é maior do que o `interval`, signinfica que as tasks estão demorando muito e estaríam sendo enfileiradas.

Acho que nesse início podemos apenas ignorar, mas no futuro pode ser que seja interessante ter implementado algumas opçõees de "algoritmos de contigência" e quem estiver escrevendo o código vai poder escolher o que será feito nessas horas.

O que acha?

**Comment by daltonmatos** [comment]
Outro ponto, acho que a task que será chamada periodicamente poderia recebre uma instância de `App`, o que acha?

se acharmos que isso pode ser opcional, antes de chama a task vamos passar pelo "parameters resolver" para descobrir se tem algum parametro tipado sendo pedido.

Apenas uma ideia. =D

Mesmo se não pasarmos isso agora, o código ainda pode fazer import da `app`, de boas.

**Comment by diogommartins** [comment]
> Outro ponto, acho que a task que será chamada periodicamente poderia recebre uma instância de `App`, o que acha?
> 
> se acharmos que isso pode ser opcional, antes de chama a task vamos passar pelo "parameters resolver" para descobrir se tem algum parametro tipado sendo pedido.
> 
> Apenas uma ideia. =D
> 
> Mesmo se não pasarmos isso agora, o código ainda pode fazer import da `app`, de boas.

Acho que é o mais "certo" mesmo. até mesmo pra mantermos a mesma interface do `run_on_startup` e `run_on_shutdown`. Como esse esquema de buscar pelos parâmetros anotados ainda não tá implementado em nenhum lugar, vou deixar essa forma pra outro momento

**Comment by daltonmatos** [comment]
Show, então por enquanto fica como parâmetro obrigatório, né?

**Comment by diogommartins** [comment]
Closed at #62
