### ISSUE TITLE
Possibilidade de passar uma listagem de erros a serem rejeitados ou recolocados na fila

### ISSUE THREAD

**Issue by lemosflavio** [B2W-BIT/async-worker#8]
Hoje o async-worker da reject em todas as mensagens caso levante uma exceção durante o processamento de um conjunto de mensagens. Esse erro que foi gerado pode ser esperado e ser necessário remove-lo da fila sem impactar no processamento das outras mensagens.

A App poderia receber uma lista com as possíveis exceções que podem ocorrer durante o processamento de uma mensagem e qual a ação que deveria ser executada, como por exemplo:

```python
App(reject_on_error=[KeyError, ValueError], requeue_on_error=[TimeoutError])
```

**Comment by daltonmatos** [comment]
@diogommartins @lemosflavio

O que pensamos foi criar duas novas opções no decorator `route()`:

`ON_SUCESS` e `ON_EXCEPTION`. As duas possuem as mesmas possibilidades de opções: `ACK`, `REJECT` ou `REQUEUE`.

Os valores default seriam:
`ON_SUCCESS=ACK`
`ON_EXCEPTION=REQUEUE`

Então poderíamos ter algo nessa linha:

```python
@app.route( ..., options={
  ActionType.ON_SUCCESS: ActionValue.ACK,
  ActionTypes.ON_EXCEPTION: ActionValue.REJECT
})
```
algo nessa linha.

**Comment by daltonmatos** [comment]
Resolvido no PR #16
