### ISSUE TITLE
Possibilidade do async-worker publicar mensagens em outra fila

### ISSUE THREAD

**Issue by lemosflavio** [B2W-BIT/async-worker#9]
Hoje o async-worker trabalha somente como consumidor e nos temos processos que são tanto consumires quanto produtores. Seria interessante se o método decorado pela App tivesse acesso a conexão que já está aberta com a fila para publicar essas mensagens de saída. Como por exemplo:

```python
from asyncworker import App

app = App(host="127.0.0.1", user="guest", password="guest", prefetch_count=256)

@app.route(["asgard/counts", "asgard/counts/errors"], vhost="fluentd")
async def drain_handler(messages, queue):
    for m in messages:
      queue.put(message.body, routing_key='new_queue')
```

**Comment by diogommartins** [comment]
O que você acha, @daltonmatos ? Faz sentido?
Parece ser só uma modificação de
```python
rv = await self._handler(all_messages)
```
para
```python
rv = await self._handler(all_messages, self.queue)
```
no no on_queue_message do consumer

**Comment by daltonmatos** [comment]
O problema é que isso força todos os handlers a receberem uma instância de queue, inclusive os handlers que não precisam publicar nada.

Acho que uma ideia possível seria o Handler ser declarado com type hint e o async worker entrega o que ele estiver pedindo.

Dessa forma posso ter um handler que recebe queue e um que não recebe. Faz sentido?

Bem no estilo dos handlers do Vibora.
